<!-- 1. __construct()
     2. __destruct()
     3. __call()
     4. __callStatic()
     5. __get()
     6. __set()
     7. __isset()
     8. __unset()
     9. __sleep()
     10.__wakeup()
     11.__serialize()
     12.__unserialize()
     13.__toString()
     14.__invoke()
     15.__set_state()
     16.__clone()
     17.__debuginfo()
  -->